site_name: AgenaIndicator Documentation
docs_dir: sources
theme: readthedocs
site_favicon: favicon.ico
extra_css: [custom.css]
use_directory_urls: true
strict: true
pages:
    - 'Lets start': 'index.md'
    - 'Data': 'data.md'
    - 'Indicators & Oscillators': 'indicators_oscillators.md'