site_name: AgenaIndicator Documentation
docs_dir: sources
theme: readthedocs
extra_css: [custom.css]
use_directory_urls: true
repo_url: https://github.com/AgenaTrader/AgenaIndicator-documentation
edit_uri: edit/master/sources/
site_url: https://agenatrader.github.io/AgenaIndicator-documentation/index.html
strict: true

google_analytics: ['UA-74646070-1', 'agenatrader.github.io']
nav:
    - 'Lets start': 'index.md'
    - 'Data': 'data.md'
    - 'Indicators & Oscillators': 'indicators_oscillators.md'
